# Generated by Django 5.0.7 on 2025-10-02 11:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Endereço de e-mail único para login e comunicação.', max_length=254, unique=True, verbose_name='E-mail')),
                ('phone_number', models.CharField(blank=True, help_text='Número de telefone para contato.', max_length=17, validators=[django.core.validators.RegexValidator(message="Número de telefone deve estar no formato: '+999999999'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('birth_date', models.DateField(blank=True, help_text='Data de nascimento do usuário.', null=True, verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(blank=True, help_text='CPF do usuário (formato: 000.000.000-00).', max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('address_line_1', models.CharField(blank=True, help_text='Rua, número e complemento.', max_length=255, verbose_name='Endereço')),
                ('address_line_2', models.CharField(blank=True, help_text='Apartamento, bloco, etc.', max_length=255, verbose_name='Complemento')),
                ('city', models.CharField(blank=True, help_text='Cidade de residência.', max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, help_text='Estado (UF) de residência.', max_length=2, verbose_name='Estado')),
                ('postal_code', models.CharField(blank=True, help_text='CEP no formato 00000-000.', max_length=9, verbose_name='CEP')),
                ('is_verified', models.BooleanField(default=False, help_text='Indica se o e-mail do usuário foi verificado.', verbose_name='E-mail Verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação da conta.', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização dos dados.', verbose_name='Última Atualização')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
